### ISSUE TITLE
Config for best accuracy stage 1 model

### ISSUE THREAD

**Issue by CVHvn** [ShadeAlsha/LTR-weight-balancing#4]
Can you give me the configuration of the best model in stage 1. You write (and in demo 1) stage 1 with 46.7% accuracy but you load weights with 47.9% accuracy .

**Comment by CVHvn** [comment]
I see that you using test time augmentation (+ flip(3) / 2), sorry because I don't read carefully :(

**Comment by ShadeAlsha** [comment]
Thanks for you interest! I am glad that you figured it out. Also, note that we choose the model that had the best validation accuracy during training, not necessarily the model at the last epoch.
